### PR TITLE
decode Changes file when reading it

### PR DESCRIPTION
**Pull request by karenetheridge**
This came about from `#distzilla` yesterday:

```
08:55 < oalders> i wanted to release a trial for WWW::Mechanize but I'm hitting an encoding issue with the Changes file https://gist.github.com/oalders/d69d28c9dad06cdce5d298cabe598092
08:55 < dipsy> [ gist:d69d28c9dad06cdce5d298cabe598092 · GitHub ] 
08:55 < oalders> dist.ini is https://github.com/libwww-perl/WWW-Mechanize/blob/master/dist.ini
08:55 < dipsy> [ WWW-Mechanize/dist.ini at master · libwww-perl/WWW-Mechanize · GitHub ] 
08:57 < Grinnz_> oalders: looks like Changes is not properly utf-8 encoded
08:57 < oalders> Grinnz_ : yeah, so i thought i allowed for that in the dist.ini
08:58 < Grinnz_> you should fix Changes instead, imo
08:59 < Grinnz_> also you probably wanted 'filename = Changes' not 'match = Changes' but that should still work
09:00 < oalders> the thing is, if i remove the encoding stuff from dist.ini entirely, the whole thing fails much earlier (with Git::GatherDir)
09:00 < oalders> so it seems like Git::GatherDir is ok with the Encoding plugin setup, but CheckChangesHasContent is not
09:04 < oalders> vim +"set nobomb | set fenc=utf8 | x" Changes
09:04 < oalders> that fixed it
09:05 < Grinnz_> i think  it's because CheckChangesHasContent operates on the file on disk, rather than the gathered file, so the Encoding plugin doesn't get applied to it
09:05 < oalders> Ah, ok.  A bit misleading that the error was suggesting the fix was in the Encoding plugin.
09:05 < Grinnz_> CheckChangesHasContent would need its own encoding option, but i don't know if that's really necessary, there's no reason for Changes to be a differnet encoding (CheckChangesHasContent is already rather strict on format)
09:06 <%ether> ewww, it looks on disk? gross!
09:06 <%ether> it ought to look in the file object in $zilla
09:06  * ether makes a note to patch.
09:06 <%ether> we've only had encodings for 3 years now; plugins ought to support it.
09:07 < Grinnz_> yeah I can't think of any reason it shouldn't just use the gathered file
```

### CODE REVIEW

**Comment by karenetheridge** [comment]
fwiw, I cannot reproduce the travis failures.  are they still there? (I don't have the privileges to poke it.)

**Comment by Grinnz** [comment]
with these changes, you should also be able to remove the usage of File::pushd and the prereq on that.

**Comment by Grinnz** [comment]
List::Util 1.33 is not required for 'first', you can just dep on List::Util 0

**Comment by karenetheridge** [comment]
I've force-pushed some updates.

**Comment by karenetheridge** [comment]
I think the travis failures are red herrings -- I can't figure out how it's getting this dependency into its head, but "Installing (without testing) Dist::Zilla~2.100950 ... Done." looks very very wrong.

**Comment by xdg** [comment]
Rebased and merged.

**Comment by karenetheridge** [comment]
thanks!

**Pull request closed without merging**
